env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions:
    - error
    - ignorePackages
    - { js: 'always' }
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  no-tabs: error
